### ISSUE TITLE
Error while running rasa with ssl certificate

### ISSUE THREAD

**Issue by gargdevesh6** [botfront/rasa-webchat#254]
Hi I am using rasa version 1.10.0. I have run the rasa server with ssl certificate and I am also getting response(Hello from Rasa: 1.10.0) on https://ip_address:5005. But when I put that link inside my website, I am getting error and I can't see any chatbot icon on the website.

See the attached .txt file for the error.
Thanks

[Chatbot Error.txt](https://github.com/botfront/rasa-webchat/files/4756455/Chatbot.Error.txt)

**Comment by MatthieuJnon** [comment]
Hi, we have several rasa instances running with ssl certificates that communicate very often with rasa webchats instances across the internet, and never had any issues with that. Please make sure that your ssl configuration and rasa configuration is right

**Comment by rahulDatahive** [comment]
I think in  your index.html of webchat , the socket url is still http://localhost:5005 instead of https://localhost:5005.
if this is the case , try correcting it. Also i think it is better to use nginx to do the reverse proxy . I tried the same thing as you are trying but even after running rasa with ssl certificates as parameters , your connection won't be secured . This was the case with me .
