### ISSUE TITLE
Adding new features help

### ISSUE THREAD

**Issue by shavone328** [botfront/rasa-webchat#421]
Hi is it possible to add new features and customize the chatbot for my personal use? I want to be able to have a user avatar, auto complete recommendations, and maybe even speech recognition. How can I go about doing this?

**Comment by rajalala** [comment]
If you are able to implement those features yourself, I'd recommend you to fork the repository and start using your own fork. That's what I did for my team's needs 😌 

There has not been recent activity on opened PRs so I don't know how likely it is to get new features in that way.
So while for example I would be willing to implement at least that user avatar, there's no guarantee it will make it into the widget (of course, might code might also just not be up to par to be merged 😅 ).

**Comment by rajalala** [comment]
@shavone328  No worries, I struggled at first as well! This is just a quick reply to get you started but I can provide more details if needed.

You are running to a `libsass` error right? That's because `libsass` (or `node-sass` or some internal dependency, I don't remember anymore) does not support Node 15 or newer. So you can get the project installed and running by downgrading Node to version 14. I'd recommend you to install `nvm` cause then you can just run `nvm use 14` each time you work with the widget.

And regarding React 17: yes, I updated React and actually made PR here (#405).

**Comment by shavone328** [comment]
@rajalala thank you! I'll try doing that and hopefully it will work. Every time I make a change to the widget and need to test it, I will have to do npm run build correct?

**Comment by rajalala** [comment]
@shavone328 no problem, hope it all works out!
You can either manually run the build (`npm run build` as you said) or use `npm run dev` to have webpack automatically rebuild the project every time you do a chance. That will run the widget configured in file `dev/index.html`. I've found that to be helpful - especially when doing style changes where I want to see results right away.

However, when with that the widget did not show up if not connected to a chatbot. To fix that you can:
* set parameter `withRules` to `false` (by default it's `true`)
* or fixing the issue of `hideWhenNotConnected` not being followed when `withRules` is `true` ([it's one line fix](https://github.com/City-of-Turku/rasa-webchat/pull/18/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R78))

**Comment by shavone328** [comment]
@rajalala ahh again thank you so much! I was so worried before that my question would just be left out into the void but you've been so helpful!

**Comment by rajalala** [comment]
@shavone328 Glad I could help 😊  If you end up having questions or issues, don't hesitate to ask! And good luck!
